name: present_unit_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  email_validator: ^3.0.0
  flutter_svg: ^2.2.1
  connectivity_plus: ^7.0.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/Fira_Sans/FiraSans-Thin.ttf
          weight: 100
        - asset: assets/Fira_Sans/FiraSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/Fira_Sans/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: assets/Fira_Sans/FiraSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/Fira_Sans/FiraSans-Light.ttf
          weight: 300
        - asset: assets/Fira_Sans/FiraSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/Fira_Sans/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/Fira_Sans/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/Fira_Sans/FiraSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/Fira_Sans/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/Fira_Sans/FiraSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/Fira_Sans/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/Fira_Sans/FiraSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Fira_Sans/FiraSans-ExtraBold.ttf
          weight: 800
        - asset: assets/Fira_Sans/FiraSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/Fira_Sans/FiraSans-Black.ttf
          weight: 900
        - asset: assets/Fira_Sans/FiraSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/Fira_Sans/FiraSans-Italic.ttf
          style: italic
